---
language: node_js
dist: trusty
node_js:
  - "stable"

sudo: false

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache  # includes bowers cache
    - node_modules

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g npm@^5.7
  - npm --version

install:
  - npm ci

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - npm test
