---
language: node_js
sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - stable

env:
  - env: EMBER_TRY_SCENARIO=ember-release
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary
  - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    - stage: "Smoke Tests"
      node_js: stable
      before_install:
        - npm config set spin false
        - npm install -g npm@6
        - npm install -g codecov
        - npm install -g greenkeeper-lockfile@1
        - npm install -g @commitlint/travis-cli
        - npm --version
      install:
        - if [[ $TRAVIS_BRANCH =~ greenkeeper || $TRAVIS_PULL_REQUEST_BRANCH =~ greenkeeper ]]; then npm install; else npm ci; fi
      before_script:
        - greenkeeper-lockfile-update
      script:
        - commitlint-travis
        - npm run lint:js
        - npm test
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - codecov --file=coveragelcov.info

    - stage: "Release"
      node_js: stable
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - npm uninstall husky
        script:
          - npx semantic-release

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
  - npm run test:node

stages:
  - "Smoke Tests"
  - test
  - name: "Release"
    if: branch = master
